config/routes.rb
Logdives::Application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" } do
    get 'users/auth/:provider' => 'users/omniauth_callbacks#passthru'
  end

  authenticate :user do
    resources :dives do
      resources :photos, :only => [:create, :destroy]
    end
    resources :users

    resources :user_uploads
    resources :buddies do
      collection do
        post 'request_confirmation'
      end
    end
    resources :buddy_confirmations
    resources :buddy_requests

    match "/clone_buddy/", :as => 'clone_buddy', :to => "buddy_confirmations#clone_buddy", :via => [:post]
    resource :log_starts

    match "/dives/new/:template", :to => "dives#new", :constraints => { :template => /.*/ }
    resource :preferences
    resources :profiles, :only => [:edit, :update]
  end



  match "/viewer/:id", :as => 'viewer', :to => "public_dives#show", :constraints => { :id => /.*/ }
  match "/latest", :as => 'latest', :to => "public_dives#index"

  resources :profiles, :only => [:show]
  match '/br/:id', :as => 'buddy_request_gateway', :to => "buddy_requests#gateway", :constraints => { :id => /.*/ }
  resources :dive_sites
  root :to => 'home#show'

end

app/controllers/buddy_confirmations_controller.rb
class BuddyConfirmationsController < ApplicationController
  respond_to :html, :js
  before_filter :load_buddy, :except => [:index]
  before_filter :check_buddy_confirmed, :only => [:clone_buddy]

  def show
    @dive = @buddy.dive(:include => [:buddies, :waypoints, :tanks, :photos])
  end

  def update
    @buddy.confirm! && @buddy.save! unless @buddy.confirmed?
    respond_with(@buddy) do |format|
      format.html { redirect_to buddy_confirmation_path(@buddy) }
      format.js
    end
  end

  def destroy
    @buddy.reject! && @buddy.save! if @buddy.awaiting_confirmation?
    respond_with(@buddy) do |format|
      format.html { redirect_to buddy_confirmation_path(@buddy) }
      format.js
    end
  end

  def clone_buddy
    @dive = Dive.reciprocate_for_buddy!(@buddy)
    respond_with(@buddy) do |format|
      format.html { redirect_to buddy_confirmation_path(@buddy) }
      format.js
    end
  end

  def index
    @buddies = current_user.buddy_confirmations.eagerly.page(params[:page]).per(50)
  end

  protected

  def load_buddy
    @buddy = Buddy.find(params[:id])
  end

  def check_buddy_confirmed
    raise ActiveRecord::RecordNotFound unless @buddy.confirmed?
  end
end

app/helpers/buddy_confirmations_helper.rb
module BuddyConfirmationsHelper
end

app/views/buddy_confirmations/_list.html.haml
.row
  .column.grid_9
    %table.list
      %th Diver
      %th Location
      %th Date
      %th You
      %tbody
      - @buddies.each do |buddy|
        %tr{:class => "#{cycle('on', 'off')}"}
          %td= link_to_profile(buddy.diver)
          %td= buddy.dive.location
          %td= buddy.dive.dive_date
          %td= link_to buddy.state.humanize,  buddy_confirmation_path(buddy)
.row
  = paginate @buddies

app/views/buddy_confirmations/_state.html.haml
#divealert
  - if buddy.awaiting_confirmation?
    = link_to "Yes, I confirm this dive", buddy_confirmation_path(:id => buddy, :format => :js), :method => :put, :remote => true
    |
    = link_to "No, I reject this dive", buddy_confirmation_path(:id => buddy, :format => :js), :method => :delete, :remote => true

  - elsif buddy.confirmed?

    %p
      = "You confirmed that #{buddy.buddy_diver_name} was on the dive.".html_safe

    - if buddy.reciprocal_dive.present?
      = "It has been added to your log as"
      = link_to "##{buddy.reciprocal_dive.dive_no} #{buddy.reciprocal_dive.location}.", edit_dive_path(buddy.reciprocal_dive), :id => 'edit_dive_link'

    - else

      You can now
      = link_to "add this dive to your log.", clone_buddy_path(:id => buddy, :format => :js), :method => :post, :remote => true, :id => :add_dive_to_log

  - elsif buddy.rejected?
    You rejected this dive. Changed you mind?
    = link_to " Confirm this dive.", buddy_confirmation_path(:id => buddy, :format => :js), :method => :put, :remote => true

app/views/buddy_confirmations/clone_buddy.js.haml
:plain

  $("#divealert").fadeOut();
  $("#divealert").html("#{escape_javascript(render(:partial => 'buddy_confirmations/state', :locals => {:buddy => @buddy}))}");
  $("#divealert").fadeIn();

app/views/buddy_confirmations/destroy.js.haml
:plain

  $("#divealert").fadeOut();
  $("#divealert").html("#{escape_javascript(render(:partial => 'buddy_confirmations/state', :locals => {:buddy => @buddy}))}")
  $("#divealert").fadeIn();
  $("#inline-buddy-#{@buddy.id}").fadeOut();
  $("#inline-buddy-#{@buddy.id}").html("#{@buddy.state.humanize}");
  $("#inline-buddy-#{@buddy.id}").fadeIn();

app/views/buddy_confirmations/index.html.haml
= render :partial => 'list'

app/views/buddy_confirmations/show.html.haml
- content_for :alerts do
  = render :partial => 'buddy_confirmations/state', :locals => {:buddy => @buddy}
= render :partial => 'public_dives/details', :locals => {:dive => @buddy.dive}

app/views/buddy_confirmations/update.js.haml
:plain
  $("#divealert").fadeOut();
  $("#divealert").html("#{escape_javascript(render(:partial => 'buddy_confirmations/state', :locals => {:buddy => @buddy}))}");
  $("#divealert").fadeIn();
  $("#inline-buddy-#{@buddy.id}").fadeOut();
  $("#inline-buddy-#{@buddy.id}").html("#{@buddy.state.humanize}");
  $("#inline-buddy-#{@buddy.id}").fadeIn();