config/routes.rb
Logdives::Application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" } do
    get 'users/auth/:provider' => 'users/omniauth_callbacks#passthru'
  end

  authenticate :user do
    resources :dives do
      resources :photos, :only => [:create, :destroy]
    end
    resources :users

    resources :user_uploads
    resources :buddies do
      collection do
        post 'request_confirmation'
      end
    end
    resources :buddy_confirmations
    resources :buddy_requests

    match "/clone_buddy/", :as => 'clone_buddy', :to => "buddy_confirmations#clone_buddy", :via => [:post]
    resource :log_starts

    match "/dives/new/:template", :to => "dives#new", :constraints => { :template => /.*/ }
    resource :preferences
    resources :profiles, :only => [:edit, :update]
  end



  match "/viewer/:id", :as => 'viewer', :to => "public_dives#show", :constraints => { :id => /.*/ }
  match "/latest", :as => 'latest', :to => "public_dives#index"

  resources :profiles, :only => [:show]
  match '/br/:id', :as => 'buddy_request_gateway', :to => "buddy_requests#gateway", :constraints => { :id => /.*/ }
  resources :dive_sites
  root :to => 'home#show'

end

app/views/shared/_context_sidebar.html.haml
- if @dive.present? && !@dive.new_record? && @dive.location.present?
  - @dive_site = DiveSite.where("site like '%#{@dive.location.split(",")[0]}%' ").where("images_hash is not null").first
- else
  - @dive_site ||= DiveSite.where("images_hash is not null").offset(rand(1000)).first


- if @dive_site
  %h4= @dive_site.name

  - if @dive_site.images_hash.present?
    - @dive_site.images_hash.each do |img|
      = link_to image_tag(img[:thumb]), img[:source], :target => '_blank', :title => img[:title]

  - if @dive_site.weblinks_hash.present?
    - @dive_site.weblinks_hash.each do |wl|
      %p
        = link_to wl[:title], wl[:source], :target => '_blank', :title => wl[:title]
        = truncate(wl[:description], :length => 100)

app/views/shared/_facebook_like.html.erb
<%
og_url =  Rails.env.production? ? "http://logdives.com/viewer/#{fb_source}" : "http://logdives.com/viewer/1-dos-ojos"
og_title = page_title(dive)
og_type = 'article'
og_image = dive.diver.avatar_url(:profile).split("?").first
og_site_name = 'Logdives'
%>

<iframe src="https://www.facebook.com/plugins/like.php?href=<%= og_url %>"
  show_faces="false" scrolling="no" frameborder="0"
  style="border:none; width:450px; height:30px"
  send="true" fb_ref="<%= fb_ref %>" fb_source="<%= fb_source %>"></iframe>

<% content_for :fb_meta_desc do -%>
<meta property="og:title" content="<%= og_title %>"/>
<meta property="og:type" content="<%= og_type %>"/>
<meta property="og:image" content="<%= og_image %>"/>
<meta property="og:url" content="<%= og_url %>"/>
<meta property="og:site_name" content="<%= og_site_name %>"/>
<% end -%>

app/views/shared/_flash.html.haml
- if flash.present?
  .row
    .column.grid_1
    .column.grid_9
      - flash.each do |key, value|
        #divealert
          = value

app/views/shared/_footer.html.haml
- if user_signed_in?
   / = link_to("Upload Dive Data", new_user_upload_path, :style => 'display:none;')
   %span#logged-in-as
      Logged in as
      = current_user.name
      |
      = link_to('Logout', destroy_user_session_path, :id => 'logout')
- else
   = link_to('Login', new_user_session_path)

|
= link_to "Contact Us", "mailto:admin@logdives.com?subject=Website%20Feedback"



|
&copy; 2011
= link_to("Logdives.com", 'http://logdives.com', :target => '_blank')

app/views/shared/_nagging.html.haml
- if current_user && current_user.name_accessor.blank?
  #divealert
    To make the most of logdives.com, please
    = link_to "choose your username", preferences_path(:only => 'username'), :class => "#{params[:only] == 'username' ? 'current' : 'notification'}"

app/views/shared/_sidebar.html.haml
#sidebar
  - unless user_signed_in?
    = render :partial => 'devise/shared/links'
  - else

    %dt
      = link_to "Log a dive", new_dive_path, :class => "#{'current' if controller_name == 'dives' && @dive  }"

    %dt
      = link_to "My Dives", dives_path, :class => "#{'current' if (controller_name == 'dives' && action_name == 'index')}", :id => 'my_dives_link'

    %dt
      = link_to 'Confirmation requests', '/buddy_requests', :class => "#{'current' if controller_name == 'buddy_confirmations' || controller_name == 'buddy_requests'}"
      - if current_user.new_buddy_requests_count > 0

        %dd
          = link_to "#{current_user.new_buddy_requests_count} new", buddy_requests_path, :class => "#{controller_name == 'buddy_requests' ? 'current' : 'notification'}"
      - if controller_name == 'buddy_confirmations' || controller_name == 'buddy_requests'
        %dd= link_to "Completed", buddy_confirmations_path, :class => "#{'current' if controller_name == 'buddy_confirmations' && action_name == 'index'}"

    %dt
      = link_to "Settings", preferences_path, :class => "#{'current' if controller_name == 'preferences'}"

  %dt
    = link_to "Dive Feed", "/latest", :class => "#{'current' if (controller_name == 'public_dives' && action_name == 'index')}"



:javascript

app/views/shared/_sign_up_nag.haml
- if !user_signed_in?
  #divealert
    - if (controller_name == 'public_dives' || controller_name == 'profiles')
      Make logdives.com your online log book.
      %p
      = link_to "Registering", "/users/sign_up"
      is quick and easy. And free.
      %p

    = link_to "Sign in with Facebook", user_omniauth_authorize_path(:facebook), :id => 'facebook_connect'