config/routes.rb
Logdives::Application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" } do
    get 'users/auth/:provider' => 'users/omniauth_callbacks#passthru'
  end

  authenticate :user do
    resources :dives do
      resources :photos, :only => [:create, :destroy]
    end
    resources :users

    resources :user_uploads
    resources :buddies do
      collection do
        post 'request_confirmation'
      end
    end
    resources :buddy_confirmations
    resources :buddy_requests

    match "/clone_buddy/", :as => 'clone_buddy', :to => "buddy_confirmations#clone_buddy", :via => [:post]
    resource :log_starts

    match "/dives/new/:template", :to => "dives#new", :constraints => { :template => /.*/ }
    resource :preferences
    resources :profiles, :only => [:edit, :update]
  end



  match "/viewer/:id", :as => 'viewer', :to => "public_dives#show", :constraints => { :id => /.*/ }
  match "/latest", :as => 'latest', :to => "public_dives#index"

  resources :profiles, :only => [:show]
  match '/br/:id', :as => 'buddy_request_gateway', :to => "buddy_requests#gateway", :constraints => { :id => /.*/ }
  resources :dive_sites
  root :to => 'home#show'

end

app/controllers/preferences_controller.rb
class PreferencesController < ApplicationController
  def show
    @user = current_user
  end
end

app/helpers/preferences_helper.rb
module PreferencesHelper
end

app/views/preferences/_email.html.haml
%fieldset
  %legend Email address
  .div
    Your email address is
    = current_user.email

    %p

app/views/preferences/_lognumbers.html.haml
= semantic_form_for @user, :url => log_starts_path, :html => {:method => :put} do |f|
  = f.inputs 'Dive numbers' do
    = f.input :log_start_no, :input_html => { :autocomplete => false, :class => 'mini-text' }, :label => "Dive numbers should start at"
    = f.commit_button 'Reset dive numbers'

app/views/preferences/_password.html.haml
= semantic_form_for(@user) do |f|
  = f.inputs 'Password' do
    = f.input :password, :input_html => { :autocomplete => false}, :label => "New password", :required => false
    = f.input :password_confirmation, :input_html => { :autocomplete => false}, :label => "New password confirmation", :required => false
    = f.commit_button 'Change password'

app/views/preferences/_profile.html.haml
= semantic_form_for @user do |f|
  = f.inputs 'Profile' do
    = link_to "Click here", edit_profile_path(current_user)
    to edit your profile

app/views/preferences/_units.html.haml
%fieldset
  %legend Units of measure
  .div
    - if @u.metric?
      You are viewing dives in Metric (bar, metres, kilos), switch to
      = link_to "Imperial (ft, lb)", {:units => 'imperial'}, :id => 'imperial'
    - else
      You are viewing dives in Imperial (psi, feet, pounds), switch to
      = link_to "Metric (bar, metres, kilos)", {:units => 'metric'}, :id => 'metric'

    %p

app/views/preferences/_username.html.haml
= semantic_form_for(@user) do |f|
  = f.inputs 'Username' do
    = f.input :name_accessor, :input_html => { :autocomplete => false}, :label => "Select a username for public display", :required => false, :hint => 'At least 4 letters'
    = "<p class='inline-errors'>The username \'#{params[:user][:name_accessor]}\' has already been taken or is invalid</p>".html_safe  if @user.errors.include?(:name)
    = f.commit_button 'Save username'

app/views/preferences/show.html.haml
.row
  .column.grid_1
  .column.grid_11

    - templates_to_render = params[:only].present? ? [params[:only]] : [:email, :units, :lognumbers, :username, :password, :profile]

    - templates_to_render.each do |t|
      = render :partial => "preferences/#{t}"